### ISSUE TITLE
Reboot always executed, before upgrade and update_reboot = no

### ISSUE THREAD

**Issue by linuxmail** [robertdebock/ansible-role-update#16]
**Describe the bug**
While executing the playbook, a reboot is always initiated even there is no reason.

**To Reproduce**
1. Run this role:

* playbook:
```yaml
---
- name: Update system
  hosts: "{{inventory}}"
  gather_facts: yes
  vars_files:
    - "{{ inventory_dir }}/group_vars/update_package.yaml"
  roles:
    - robertdebock.update
    - systemli.needrestart
```
* group_vars/update_package.yaml
```yaml
# Update system related
---

## robertdebock
update_reboot: false
reboot_always: no
update_autoremove: yes
update_upgrade_command: safe

## systemli
needrestart_disable_email: 1
needrestart_action: a
needrestart_blacklist_rc:
  - mongodb-.*\.service
  - mariadb\.service
  - mysql\.service
```
* Run
```bash
$ ansible-playbook update_system.yaml -i inventories/dev/hosts --extra-vars "inventory=devpc21" --limit "devpc21n-06"
```

2. See error
```
PLAY [Update system] ***********************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [devpc21n-06]

TASK [robertdebock.reboot : see if a reboot is required] ***********************************************************************************
skipping: [devpc21n-06]

TASK [robertdebock.reboot : reboot the machine] ********************************************************************************************
changed: [devpc21n-06]

RUNNING HANDLER [robertdebock.reboot : 1 wait for the start of reboot] *********************************************************************
Pausing for 4 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [devpc21n-06]

RUNNING HANDLER [robertdebock.reboot : 2 wait for the machine to be up] ********************************************************************
ok: [devpc21n-06]

RUNNING HANDLER [robertdebock.reboot : 3 gather facts after reboot] ************************************************************************
ok: [devpc21n-06]
```

The host reboots and then update task is running. In case of a new kernel, libc etc. a 2nd reboot is required. 

**Expected behavior**
1. Don't reboot
2. Update system

**Error**
* More debug -vvv
```
META: ran handlers
Read vars_file '{{ inventory_dir }}/group_vars/update_package.yaml'

TASK [robertdebock.reboot : see if a reboot is required] *************************************************************************************************************************************************************************************
task path: /home/dfuchs/git/ansible-new/roles/robertdebock.reboot/tasks/main.yml:3
skipping: [devpc21n-06] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
META: ran handlers
Read vars_file '{{ inventory_dir }}/group_vars/update_package.yaml'

TASK [robertdebock.reboot : reboot the machine] **********************************************************************************************************************************************************************************************
task path: /home/dfuchs/git/ansible-new/roles/robertdebock.reboot/tasks/main.yml:22
fatal: [devpc21n-06]: FAILED! => {
    "changed": false,
    "msg": "check mode and async cannot be used on same task."
}
...ignoring
META: ran handlers
Read vars_file '{{ inventory_dir }}/group_vars/update_package.yaml'
```

**Environment**
- Control node OS: Fedora 30 Workstation
- Control node Ansible version: 2.8
- Managed node OS:  Debian 9

**Additional context**
I want to let needrestart to restart services and maybe the system.
