### ISSUE TITLE
update_kernel_reboot_only = yes

### ISSUE THREAD

**Issue by linuxmail** [robertdebock/ansible-role-update#17]
**Is your feature request related to a problem? Please describe.**
We have every end of a month a bigger system upgrade on round about ~120 hosts. In most cases, we do `update_reboot = yes` and let the hosts reboot.
But we have also auto updates, via Rundeck every day, which executes the same playbook, with your great modules :-) But ... also with `update_reboot = yes`, which reboots the hosts also, if only PHP package or something like that was upgraded :-).

**Describe the solution you'd like**
It would be very cool, if a new global variable exists, like `update_kernel_reboot_only = yes`, that do not reboot while a normal package update, but if the kernel has changed. For that, we can ask robertdebock.reboot, if we have a kernel change pending.

**Describe alternatives you've considered**
I would starting with having two kind of playbooks, one with reboot, one with not. Also possible: adding the variable while calling the playbook (wia Rundeck or  shell) , but than you have instruct all people who are involved.

**Additional context**

Our playbooks for upgrades looks like this one:

```yaml
---
# Generic update System playbook

- name: Update system
  hosts: "{{inventory}}"
  serial: 1
  gather_facts: yes
  vars_files:
    - "{{inventory_dir}}/group_vars/update_package.yaml"
  tasks:
    - name: Update packages
      include_role:
        name: robertdebock.update
    - name: Execute puppet if installed
      include_role:
        name: puppet
    - name: Check for needrestart services
      include_role:
        name: systemli.needrestart
    - name: Execute puppet if installed
      include_role:
        name: puppet
    - name: Run Rkhunter if installed
      include_role:
        name: rkhunter
```
The (inventories/dev/)group_vars/update_package.yaml:

```yaml
---
## robertdebock
update_autoremove: yes
update_upgrade_command: safe

reboot_always: no
update_reboot: yes

## systemli
needrestart_disable_email: 1
needrestart_action: a
needrestart_blacklist_rc:
  - mongodb-.*\.service
  - mariadb\.service
  - mysql\.service
````

The command:

```
ansible-playbook update_system_test.yaml  -i inventories/dev/hosts --extra-vars "inventory=devpc21" --limit devpc21n-05.example.local
```
