### ISSUE TITLE
Post upgrade reboot behavior options

### ISSUE THREAD

**Issue by ahnooie** [robertdebock/ansible-role-update#9]
# Option to control post upgrade reboot behavior

What do you think about adding an option to control the reboot behavior?  I can think of 3 options I would use:

1. update_unattended_reboot = always (current behavior/default)
2. update_unattended_reboot = never
3. update_unattended_reboot = when_required

Option 3 might be a little tricky...

For Debian/Ubuntu /var/run/reboot-required is created whenever a reboot is needed: (could be implemented adding the "removes" option, something like the example below)
```
- name: reboot when required
  shell: (sleep "{{ update_reboot_delay }}" && shutdown -r now "ansible-role-update" &)
  async: 1
  poll: 0
  ignore_errors: yes
  changed_when: no
  removes=/var/run/reboot-required
  when:
    - ansible_virtualization_type != "docker"
    - update_unattended_reboot = "when_required"
```

For Fedora/RedHat/CentOS I believe there's a needs-restarting command that can be installed.
